- name: Setup Arch Linux System (Common)
  hosts: localhost
  become: true
  vars:
    playbook_dir: "/home/frank/.local/share/chezmoi/dot_local/share/chezmoi/playbook"
    script_dir: "{{ playbook_dir }}/scripts"
    service_dir: "{{ playbook_dir }}/services"
    aur_packages:
      - 7zip
      - adw-gtk-theme
      - ansible
      - archinstall
      - base
      - base-devel
      - beekeeper-studio-bin
      - bun-bin
      - catppuccin-gtk-theme-mocha
      - catppuccin-sddm-theme-mocha
      - chezmoi
      - devt-git
      - discord
      - docker
      - dolphin
      - etcher-bin
      - filezilla
      - firefox
      - flutter-bin
      - git
      - gparted
      - grub
      - gwenview
      - htop
      - kitty
      - libreoffice-fresh
      - linux
      - linux-firmware
      - linux-lts
      - man-db
      - man-pages
      - mariadb
      - nano
      - neofetch
      - neovim
      - net-tools
      - networkmanager-openvpn
      - nodejs
      - noto-fonts-emoji
      - npm
      - nvtop
      - obs-studio
      - obsidian
      - openvpn
      - papirus-icon-theme
      - paru
      - paru-debug
      - postman-bin
      - powertop
      - python-pip
      - python-pyxdg
      - python-requests
      - python-yaml
      - qbittorrent
      - rpi-imager
      - sddm
      - simple-sddm-theme-2-git
      - simple-sddm-theme-git
      - spotify
      - thunar
      - thunderbird
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
      - ttf-ubuntu-mono-nerd
      - ttf-ubuntu-nerd
      - vim
      - visual-studio-code-bin
      - vlc
      - wget
      - woff2-font-awesome
      - yay
      - yay-debug
      - zsh

  tasks:
    - name: update the system
      shell: sudo pacman -Syu --noconfirm
      tags: update

    - name: Install AUR Helper (yay)
      shell: "{{ script_dir }}/install_helper.sh"
      tags: Helper

    - name: Ensure yay is installed
      community.general.pacman:
        name: yay
        state: present

    - name: Install AUR packages
      shell: yay -S --noconfirm {{ item }}
      loop: "{{ aur_packages }}"
      tags: aur
      when: ansible_distribution == 'Arch Linux'

    - name: Install lazyvim
      shell: "{{ script_dir }}/install_lazyvim.sh"
      tags: lazyvim

    - name: Setting up Grub
      shell: "{{ script_dir }}/grub_setup.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: grub

    - name: Setting up SDDM
      shell: "{{ script_dir }}/set_sddm_theme.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: sddm

    - name: Setting up qemu
      shell: "{{ script_dir }}/virt_config.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: qemu
