- name: Setup Arch Linux
  hosts: localhost
  become: true
  vars:
    playbook_dir: "/home/frank/.playbook"
    script_dir: "{{ playbook_dir }}/scripts"
    service_dir: "{{ playbook_dir }}/services"
    aur_packages:
      - hyprland
      - hyprlock
      - hyprpicker
      - hyprpaper
      - hypridle
      - hyprshot
      - swaync
      - waybar
      - wlogout
      - wofi
      - firefox
      - thunar
      - kitty
      - zsh
      - gwenview
      - plasma-nm
      - qt6ct
      - qt5ct
      - qt5-wayland
      - qt6-wayland
      - adw-gtk-theme
      - papirus-icon-theme
      - catppuccin-gtk-theme-mocha
      - catppuccin-sddm-theme-mocha
      - ttf-font-awesome
      - ttf-ubuntu-mono-nerd
      - ttf-ubuntu-nerd
      - simple-sddm-theme-2-git
      - wget
      - curl
      - neofetch
      - nvtop
      - htop
      - radeontop
      - nwg-look
      - man-db
      - man-pages
      - pamixer
      - pavucontrol
      - blueman
      - blueberry
      - bluez
      - bluez-utils
      - git
      - neovim
      - docker
      - mariadb
      - go
      - rust
      - nodejs
      - postman-git
      - beekeeper-studio-bin
      - bun-bin
      - discord
      - qbittorrent
      - thunderbird
      - steam
      - obs-studio
      - obsidian
      - vlc
      - etcher-bin


  tasks:
    - name: update the system
      shell: sudo pacman -Syu --noconfirm
      tags: update

    - name: Ensure yay is installed
      community.general.pacman:
        name: yay
        state: present

    - name: Install AUR packages
      shell: yay -S --noconfirm {{ item }}
      loop: "{{ aur_packages }}"
      tags: aur
      when: ansible_distribution == 'Arch Linux'

    - name: Deploy disable_usb script and service
      shell: "{{ script_dir }}/disable_usb.sh"
      tags: disable_usb

    - name: Mouting storage drive automatically
      shell: "{{ script_dir }}/mounting_drive.sh"
      tags: storage

    - name: Install AUR Helper (yay)
      shell: "{{ script_dir }}/install_helper.sh"
      tags: Helper

    - name: Install lazyvim
      shell: "{{ script_dir }}/install_lazyvim.sh"
      tags: lazyvim

    - name: Install Cider V2
      shell: "{{ script_dir }}/install_cider.sh"
      tags: cider

    - name: Setting up Grub
      shell: "{{ script_dir }}/grub_setup.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: grub

    - name: Setting up SDDM
      shell: "{{ script_dir }}/set_sddm_theme.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: sddm

    - name: Setting up qemu
      shell: "{{ script_dir }}/virt_config.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: qemu

  
