- name: Setup Arch Linux Desktop (Hyprland)
  hosts: localhost
  become: true
  vars:
    playbook_dir: "/home/frank/.local/share/chezmoi/dot_playbook"
    script_dir: "{{ playbook_dir }}/scripts"
    service_dir: "{{ playbook_dir }}/services"
    aur_packages:
      - 7zip
      - adw-gtk-theme
      - amd-ucode
      - ansible
      - archinstall
      - base
      - base-devel
      - beekeeper-studio-bin
      - blueberry
      - blueman
      - bluez
      - bluez-utils
      - breeze5
      - bridge-utils
      - bun-bin
      - catppuccin-gtk-theme-mocha
      - catppuccin-sddm-theme-mocha
      - chezmoi
      - dconf-editor
      - devt-git
      - discord
      - dnsmasq
      - docker
      - dolphin
      - dunst
      - etcher-bin
      - filezilla
      - firefox
      - flutter-bin
      - gamescope
      - git
      - glow
      - gparted
      - grim
      - grub
      - gst-plugin-pipewire
      - gucharmap
      - gwenview
      - htop
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprshot
      - iw
      - iwd
      - kconfig5
      - kcoreaddons5
      - ki18n5
      - kitty
      - kwidgetsaddons5
      - libpulse
      - libreoffice-fresh
      - linux
      - linux-firmware
      - linux-lts
      - mage
      - man-db
      - man-pages
      - mariadb
      - mdcat
      - nano
      - neofetch
      - neovim
      - net-tools
      - network-manager-applet
      - networkmanager
      - networkmanager-openvpn
      - nodejs
      - noto-fonts-emoji
      - npm
      - nvtop
      - nwg-look
      - obs-studio
      - obsidian
      - openbsd-netcat
      - openvpn
      - os-prober
      - pamixer
      - papirus-icon-theme
      - paru
      - paru-debug
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - plasma-nm
      - plasma-pa
      - plasma-workspace
      - polkit-kde-agent
      - polkit-qt5
      - postman-bin
      - powertop
      - python-pip
      - python-pyxdg
      - python-requests
      - python-yaml
      - qbittorrent
      - qemu-desktop
      - qt5-quickcontrols2
      - qt5-tools
      - qt5-wayland
      - qt5ct
      - qt6-wayland
      - qt6ct
      - qtermwidget
      - radeontop
      - rpi-imager
      - sddm
      - simple-sddm-theme-2-git
      - simple-sddm-theme-git
      - slurp
      - smartmontools
      - spice-vdagent
      - spotify
      - steam
      - stow
      - swaync
      - thunar
      - thunderbird
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
      - ttf-ubuntu-mono-nerd
      - ttf-ubuntu-nerd
      - udiskie
      - vde2
      - vim
      - virt-manager
      - virt-viewer
      - visual-studio-code-bin
      - vlc
      - vulkan-radeon
      - waybar
      - wev
      - wget
      - wireless_tools
      - wireplumber
      - wlogout
      - woff2-font-awesome
      - wofi
      - xclip
      - xdg-desktop-portal-hyprland
      - xdg-utils
      - xf86-video-amdgpu
      - xf86-video-ati
      - xorg-server
      - xorg-xinit
      - xpadneo-dkms
      - yay
      - yay-debug
      - zram-generator
      - zsh

  tasks:
    - name: update the system
      shell: sudo pacman -Syu --noconfirm
      tags: update

    - name: Ensure yay is installed
      community.general.pacman:
        name: yay
        state: present

    - name: Install AUR packages
      shell: yay -S --noconfirm {{ item }}
      loop: "{{ aur_packages }}"
      tags: aur
      when: ansible_distribution == 'Arch Linux'

    - name: Deploy disable_usb script and service
      shell: "{{ script_dir }}/disable_usb.sh"
      tags: disable_usb

    - name: Mouting storage drive automatically
      shell: "{{ script_dir }}/mounting_drive.sh"
      tags: storage

    - name: Install AUR Helper (yay)
      shell: "{{ script_dir }}/install_helper.sh"
      tags: Helper

    - name: Install lazyvim
      shell: "{{ script_dir }}/install_lazyvim.sh"
      tags: lazyvim

    - name: Install Cider V2
      shell: "{{ script_dir }}/install_cider.sh"
      tags: cider

    - name: Setting up Grub
      shell: "{{ script_dir }}/grub_setup.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: grub

    - name: Setting up SDDM
      shell: "{{ script_dir }}/set_sddm_theme.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: sddm

    - name: Setting up qemu
      shell: "{{ script_dir }}/virt_config.sh"
      when: ansible_distribution == 'Arch Linux'
      tags: qemu
