- name: Setup Ubuntu Laptop (Gnome)
  hosts: localhost
  become: true
  vars:
    playbook_dir: "/home/frank/.local/share/chezmoi/dot_playbook"
    script_dir: "{{ playbook_dir }}/scripts"
    service_dir: "{{ playbook_dir }}/services"
    apt_packages:

    snap_packages:
      - chezmoi --classic
      - discord
      - go --classic


  tasks:
    - name: update the system
      shell: sudo apt update -y && sudo apt full-upgrade -y
      tags: update

    - name: Install apt packages
      shell: sudo apt install -y {{ item }}
      loop: "{{ apt_packages }}"
      tags: apt
      when: ansible_distribution == 'Ubuntu'

    - name: Install Snap packages
      shell: sudo snap install {{ item }}
      loop: "{{ snap_packages }}"
      when: ansible_distribution == 'Ubuntu'

    - name: Install lazyvim
      shell: "{{ script_dir }}/install_lazyvim.sh"
      tags: lazyvim

    - name: Setting up ZSH (Oh-My-Posh + Powerlevel10k)
      shell: "{{ script_dir }}/setting_up_zsh.sh"
      tags: zsh

    - name: Install Docker
      shell: "{{ script_dir }}/docker_ubuntu_install.sh"
      tags: docker
      when: ansible_distribution == 'Ubuntu'

